"""
Picasso Average plugin: 2D in-plane rotation + 3D translation alignment
of picked structures, with a reference channel whose transformations can
be replayed onto a target channel.

--------------------------------------------------------------------------------
Installation
--------------------------------------------------------------------------------
Drop this file into Picasso's plugin directory:

    ~/.picasso/plugins/           (Linux / macOS)
    %USERPROFILE%\\.picasso\\plugins\\  (Windows)

Restart Picasso, open the *Average* window, and you will find the plugin
under the ``Plugins`` menu.

--------------------------------------------------------------------------------
Workflow overview
--------------------------------------------------------------------------------
This plugin implements the standard two-channel averaging alignment used
for correlative SMLM:

1. **Reference channel alignment** - ``3D COM & 2D rotation cross-correlation``
   * Every group (picked structure) is centered on its own 3D center of mass.
   * The group is then iteratively aligned to the consensus (reference)
     histograms by searching for the in-plane rotation and 3D translation
     that maximize cross-correlation with the current average.
   * The final aligned reference localizations are written as
     ``<basename>_3DAligned.hdf5`` and the per-group transforms as
     ``<basename>_3DTransformations.yaml``.

2. **Target channel alignment** - ``Apply saved reference transformations
   to target channel``
   * Reads the transform YAML produced in step 1.
   * Replays the exact same rigid transforms (COM, rotation, translation)
     on a second channel, using ``group`` id as the correspondence key.
   * Writes ``<basename>_3DAligned.hdf5`` for the target.

This two-step design means the target channel never re-aligns; it is
*carried along* by the reference. That is the standard way to preserve
relative registration between two channels in correlative SMLM.

--------------------------------------------------------------------------------
Coordinate and unit conventions (must match ``picasso.gui.average``)
--------------------------------------------------------------------------------
* Localizations are held in a ``pandas.DataFrame`` with columns:
    - ``x``, ``y`` : camera pixels (float)
    - ``z``        : nanometers (float)
    - ``group``    : integer, one per picked structure
* While averaging, groups are centered on the origin. The canvas offset
  (``Width / 2``, ``Height / 2``) is added only on save, by
  ``picasso.average.prepare_locs_for_save``. This mirrors exactly what the
  built-in Average plugin does, so downstream features (File > Save,
  Process > Average, undo, etc.) keep working.
* Histogram bin edges for cross-correlation are in **nanometers**;
  ``align_group`` converts camera-pixel x/y into nm before binning.

--------------------------------------------------------------------------------
Threading model
--------------------------------------------------------------------------------
* The heavy alignment runs in a dedicated ``QThread`` (``AlignWorker``) so
  the GUI stays responsive.
* Within each iteration, groups are aligned in parallel using a
  ``ThreadPoolExecutor``. Each thread does NumPy/SciPy work that releases
  the GIL, so we get real parallelism without the cost of forking.
* ``threadpoolctl`` caps BLAS/OpenMP backends to one thread per worker,
  preventing the classic oversubscription (N_workers x N_BLAS_threads)
  that degrades performance and sometimes crashes on large grids.

author: Aditya Chhatre
"""

from __future__ import annotations

import contextlib
import os
import traceback
from concurrent.futures import ThreadPoolExecutor, as_completed

import numpy as np
import pandas as pd
import yaml
from PyQt6 import QtCore, QtWidgets
from scipy.ndimage import rotate
from scipy.signal import fftconvolve

from picasso import __version__, average, io, lib

try:  # keep BLAS/FFT backends single-threaded inside our own thread pool
    from threadpoolctl import threadpool_limits
except ImportError:  # pragma: no cover - threadpoolctl ships with scipy stacks
    threadpool_limits = None

# -----------------------------------------------------------------------------
# Tunable constants
# -----------------------------------------------------------------------------
# In-plane rotation search: a coarse sweep finds the basin, then a fine
# sweep refines the peak. This two-stage strategy is ~10x faster than a
# single 1-degree scan over the full 360-degree circle and is just as
# accurate for the roughly symmetric structures typical of picked SMLM
# data. Adjust only if your structures have very sharp angular features.
ANGLE_COARSE_STEP = 5.0  # degrees
ANGLE_FINE_STEP = 1.0    # degrees

# Name used in the "Generated by" metadata and in error dialogs. Kept
# distinct from the built-in Average plugin so users can tell which
# alignment produced a given file.
PLUGIN_NAME = "3D Average Transform"


def _single_threaded_blas():
    """Stop BLAS/FFT backends from oversubscribing inside our thread pool.

    Setting ``OMP_NUM_THREADS`` & co. at import time would be both too late
    (NumPy is already loaded in the GUI process) and too broad (it would
    affect the whole application), so the limit is scoped to the pool.

    When ``threadpoolctl`` is unavailable (rare; it is a transitive
    dependency of SciPy), a no-op context manager is returned so the
    plugin still works, just possibly slower on machines with many cores.
    """
    if threadpool_limits is None:
        return contextlib.nullcontext()
    return threadpool_limits(limits=1)


# =============================================================================
# Core alignment (no GUI, no globals - safe to call from worker threads)
# =============================================================================
# The functions below form a pure numerical core with no Qt, no global
# state, and no I/O. They can therefore be unit-tested, reused in scripts,
# and safely executed from worker threads or processes.


def group_indices(locs: pd.DataFrame) -> dict[int, np.ndarray]:
    """Map each group id to the positional indices of its localizations.

    ``DataFrame.groupby(...).indices`` already returns exactly this, but we
    force Python ``int`` keys and ``int64`` index arrays so the result can
    be passed across thread boundaries without dtype surprises.
    """
    return {
        int(g): np.asarray(idx, dtype=np.int64)
        for g, idx in locs.groupby("group").indices.items()
    }


def rotation_search(hist_2d: np.ndarray, ref_2d: np.ndarray) -> float:
    """Return the in-plane angle (degrees) maximizing the 2D overlap.

    ``hist_2d`` and ``ref_2d`` are xy histograms on the same grid, with
    axis 0 = x and axis 1 = y. The returned angle is the one to apply to
    the group's coordinates with the standard counter-clockwise matrix
    ``[[cos, -sin], [sin, cos]]``, which matches how
    ``scipy.ndimage.rotate`` moves image content for these axes.

    Two-stage search:

    1. Coarse sweep over ``[0, 360)`` in ``ANGLE_COARSE_STEP`` increments.
    2. Fine sweep over ``best +/- ANGLE_COARSE_STEP`` in ``ANGLE_FINE_STEP``
       increments.

    The output is always normalized to ``[0, 360)`` so it composes cleanly
    across iterations in :func:`compose`.
    """

    def best_of(angles):
        # Return the angle maximizing the sum of element-wise product with
        # the reference (unnormalized cross-correlation). No normalization
        # is needed because all candidate rotations have identical total
        # intensity (rotation preserves the sum), so the raw product is a
        # monotonic proxy for normalized correlation.
        best_angle, best_cc = 0.0, -np.inf
        for angle in angles:
            rotated = rotate(hist_2d, angle, reshape=False, order=1)
            cc = float(np.sum(rotated * ref_2d))
            if cc > best_cc:
                best_cc, best_angle = cc, float(angle)
        return best_angle, best_cc

    coarse, _ = best_of(np.arange(0.0, 360.0, ANGLE_COARSE_STEP))
    fine, _ = best_of(
        np.arange(
            coarse - ANGLE_COARSE_STEP,
            coarse + ANGLE_COARSE_STEP + 1e-9,
            ANGLE_FINE_STEP,
        )
    )
    return float(fine % 360.0)


def align_group(
    x_cam: np.ndarray,
    y_cam: np.ndarray,
    z_nm: np.ndarray,
    ref_hist: np.ndarray,
    ref_2d: np.ndarray,
    edges: np.ndarray,
    pixel_size: float,
) -> tuple[float, float, float, float]:
    """Align one group to the reference maps.

    This is the numerical heart of the plugin. For a single picked
    structure it returns the rigid transform (in-plane angle + 3D
    translation) that best matches the current consensus. The caller is
    responsible for actually applying the transform and for accumulating
    it in the per-group transform record.

    Parameters
    ----------
    x_cam, y_cam : np.ndarray
        Group coordinates in camera pixels, centered on the origin.
    z_nm : np.ndarray
        Group z coordinates in nm, centered on the origin.
    ref_hist : np.ndarray
        3D histogram of all localizations on the ``edges`` grid (nm).
    ref_2d : np.ndarray
        ``ref_hist`` summed along z.
    edges : np.ndarray
        Shared bin edges in nm for all three axes. Must be identical for
        the reference and the group so that voxels correspond 1:1.
    pixel_size : float
        Camera pixel size in nm, used to convert x/y to nm before binning.

    Returns
    -------
    angle_deg : float
        In-plane rotation to apply to the group (counter-clockwise,
        degrees, in ``[0, 360)``).
    dx_cam, dy_cam : float
        Translation in camera pixels, applied *after* the rotation.
    dz_nm : float
        Translation in nm along z.

    Notes
    -----
    * A group that lies entirely outside the histogram box returns the
      identity transform. This is preferable to crashing on a single
      badly-picked group, and its COM was already correctly subtracted by
      the caller.
    * Only one round of (rotation -> translation) is performed here. The
      iteration needed to converge on the consensus is done by the caller
      in :meth:`AlignWorker._run`; this keeps ``align_group`` free of any
      state and easy to parallelize.
    """
    # Histogram the group in xy on the shared edges. Converting to nm here
    # (rather than binning in pixels) makes the histogram directly
    # comparable to the reference.
    hist_2d, _, _ = np.histogram2d(
        x_cam * pixel_size, y_cam * pixel_size, bins=(edges, edges)
    )
    if not hist_2d.any():  # group entirely outside the box - leave it alone
        return 0.0, 0.0, 0.0, 0.0

    angle_deg = rotation_search(hist_2d, ref_2d)

    # Apply the rotation in *coordinate* space (not image space) so the
    # convention matches ``rotation_search`` and, ultimately, the way the
    # transform is later replayed on the target channel.
    rad = np.radians(angle_deg)
    cos_a, sin_a = np.cos(rad), np.sin(rad)
    x_rot = x_cam * cos_a - y_cam * sin_a
    y_rot = x_cam * sin_a + y_cam * cos_a

    # Histogram the rotated group in 3D and cross-correlate with the
    # reference. Because both histograms use the same ``edges``, the lag
    # of the peak directly gives the translational offset.
    hist_3d, _ = np.histogramdd(
        (x_rot * pixel_size, y_rot * pixel_size, z_nm),
        bins=(edges, edges, edges),
    )
    if not hist_3d.any():
        return angle_deg, 0.0, 0.0, 0.0

    # Cross-correlation as a convolution with the reversed group histogram.
    # ``mode="same"`` puts zero lag at ``shape // 2`` for both even and odd
    # bin counts, so the shift is simply the peak offset from that center.
    cc_3d = fftconvolve(ref_hist, hist_3d[::-1, ::-1, ::-1], mode="same")
    peak = np.unravel_index(np.argmax(cc_3d), cc_3d.shape)
    shift_bin = np.asarray(peak) - np.asarray(cc_3d.shape) // 2

    # Use the true bin width: ``edges`` may not be an exact multiple of the
    # requested voxel size.
    bin_width = float(edges[1] - edges[0])
    return (
        angle_deg,
        float(shift_bin[0] * bin_width / pixel_size),
        float(shift_bin[1] * bin_width / pixel_size),
        float(shift_bin[2] * bin_width),
    )


def compose(
    transform: dict, angle_deg: float, dx: float, dy: float, dz: float
) -> None:
    """Fold one more iteration into a group's accumulated transform.

    Iteration *k* maps ``p -> R_k p + d_k``, so after *n* iterations the
    composite is ``R_n...R_1 p + sum_k (R_n...R_(k+1) d_k)``: the angles
    add, but every translation must be rotated by the rotations that come
    after it. Summing the raw translations (as a naive accumulator does)
    misplaces the target channel whenever a later iteration finds a
    non-zero angle.

    The function mutates ``transform`` in place. Angles are kept in
    ``[0, 360)`` for readability; translations are in the same units as
    the input (camera pixels for x/y, nm for z).
    """
    rad = np.radians(angle_deg)
    cos_a, sin_a = np.cos(rad), np.sin(rad)
    tx, ty = transform["dx"], transform["dy"]
    # New cumulative rotation is the product of the previous one and the
    # new one; angles are additive because we only rotate about z.
    transform["angle_deg"] = float(
        (transform["angle_deg"] + angle_deg) % 360.0
    )
    # Rotate the *old* translation by the *new* rotation before adding the
    # new translation, so that the total still equals R_total * p + d_total.
    transform["dx"] = float(tx * cos_a - ty * sin_a + dx)
    transform["dy"] = float(tx * sin_a + ty * cos_a + dy)
    transform["dz"] = float(transform["dz"] + dz)


def apply_transform(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    com: dict,
    cc: dict,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Apply a recorded transform: center on the reference COM, then
    rotate in plane and translate. Returns origin-centered coordinates.

    This is the exact inverse of the operation performed during the
    reference alignment, which is what makes channel-to-channel replay
    possible.
    """
    # Step 1: bring the group to its own center of mass (the same COM that
    # was subtracted from the reference group during alignment).
    x = np.asarray(x, dtype=np.float64) - com["com_x"]
    y = np.asarray(y, dtype=np.float64) - com["com_y"]
    z = np.asarray(z, dtype=np.float64) - com["com_z"]

    # Step 2: apply the accumulated rigid transform.
    rad = np.radians(cc["angle_deg"])
    cos_a, sin_a = np.cos(rad), np.sin(rad)
    return (
        x * cos_a - y * sin_a + cc["dx"],
        x * sin_a + y * cos_a + cc["dy"],
        z + cc["dz"],
    )


# =============================================================================
# Metadata and I/O
# =============================================================================
# These helpers translate between the plugin's internal DataFrame and the
# on-disk format expected by Picasso. They deliberately delegate to
# ``picasso.average`` and ``picasso.io`` so that files saved here are
# byte-compatible with the built-in Average plugin.


def ensure_required_metadata(
    info: list[dict], locs: pd.DataFrame, pixel_size: float
) -> list[dict]:
    """Return a copy of ``info`` with the keys Picasso requires downstream.

    ``lib.ensure_sanity`` needs ``Width``, ``Height`` and ``Frames``, and
    ``average.prepare_locs_for_save`` needs ``Width``/``Height`` to place
    the structure on the canvas. Existing values are never overwritten -
    only genuinely missing ones are filled in, so acquisition metadata
    stays intact.

    The localizations are expected to be origin-centered when this is
    called; ``Width``/``Height`` are computed from the extent of the
    data around the origin, which is a reasonable default for picked
    structures that have already been COM-aligned.
    """
    info = [dict(entry) for entry in (info or [{}])]
    first = info[0]
    if lib.get_from_metadata(info, "Width") is None:
        first["Width"] = int(np.ceil(locs["x"].max() - locs["x"].min())) or 1
    if lib.get_from_metadata(info, "Height") is None:
        first["Height"] = int(np.ceil(locs["y"].max() - locs["y"].min())) or 1
    if lib.get_from_metadata(info, "Frames") is None:
        first["Frames"] = (
            int(locs["frame"].max()) + 1 if "frame" in locs.columns else 1
        )
    if lib.get_from_metadata(info, "Pixelsize") is None:
        first["Pixelsize"] = float(pixel_size)
    return info


def save_aligned_locs(
    path: str, locs: pd.DataFrame, info: list[dict], params: dict
) -> None:
    """Save origin-centered localizations the way the Average GUI does.

    ``prepare_locs_for_save`` shifts x/y onto the canvas
    (``+Width/2``, ``+Height/2``) and appends a provenance entry, which is
    then extended with this plugin's parameters.

    The ``Generated by`` string is deliberately set to ``Picasso <ver>
    Average`` (not the plugin name) so that the file loads without
    warnings in older Picasso versions that check this field, and so that
    the plugin is listed separately under its own key.
    """
    out_locs, out_info = average.prepare_locs_for_save(locs.copy(), info)
    out_info[-1]["Generated by"] = f"Picasso {__version__} Average"
    out_info[-1][PLUGIN_NAME] = params
    io.save_locs(path, out_locs, out_info)


def load_transformations(path: str) -> tuple[dict[int, dict], dict]:
    """Read a ``*_3DTransformations.yaml`` file.

    Returns the per-group transforms plus the ``__meta__`` block (empty
    for files written before it existed). Group entries are normalized to
    the nested ``com_transform``/``cc_transform`` layout, so callers do
    not have to know which plugin version produced the file.

    Two on-disk layouts are supported:

    * **Current** - ``{group: {com_transform: {...}, cc_transform: {...}}}``
    * **Legacy** - flat dictionaries with keys ``com_x``, ``angle_deg``,
      etc., as written by early versions of this plugin.
    """
    with open(path, "r") as f:
        docs = [d for d in yaml.safe_load_all(f) if isinstance(d, dict)]

    raw: dict = {}
    for doc in docs:
        raw.update(doc)

    meta = raw.pop("__meta__", {}) or {}
    transformations: dict[int, dict] = {}
    for key, entry in raw.items():
        try:
            group = int(key)
        except (TypeError, ValueError):
            continue
        if not isinstance(entry, dict):
            continue
        if "com_transform" in entry and "cc_transform" in entry:
            com, cc = entry["com_transform"], entry["cc_transform"]
        else:  # flat layout written by older versions of this plugin
            com = {k: entry.get(k, 0.0) for k in ("com_x", "com_y", "com_z")}
            cc = {
                k: entry.get(k, 0.0) for k in ("angle_deg", "dx", "dy", "dz")
            }
        transformations[group] = {"com_transform": com, "cc_transform": cc}
    return transformations, meta


# =============================================================================
# GUI plumbing
# =============================================================================


class ParametersDialog(lib.Dialog):
    """Single dialog for all alignment parameters.

    All four parameters are exposed up front so the user can reason about
    the trade-off between spatial resolution (voxel size), convergence
    quality (iterations), and memory (box size / voxel size).
    """

    def __init__(self, parent, pixel_size: float):
        super().__init__(parent)
        self.setWindowTitle("3D alignment parameters")
        grid = QtWidgets.QGridLayout(self)

        def add_row(row, label, widget, tooltip):
            item = QtWidgets.QLabel(label)
            item.setToolTip(tooltip)
            widget.setToolTip(tooltip)
            grid.addWidget(item, row, 0)
            grid.addWidget(widget, row, 1)

        # -- Camera pixel size ---------------------------------------------
        # Default comes from the HDF5 metadata; the user can override it
        # for datasets with unusual or missing pixel-size metadata.
        self.pixel_size = QtWidgets.QDoubleSpinBox()
        self.pixel_size.setRange(1.0, 1000.0)
        self.pixel_size.setDecimals(2)
        self.pixel_size.setValue(pixel_size)
        add_row(
            0,
            "Camera pixel size (nm):",
            self.pixel_size,
            "Used to convert x/y (camera pixels) to nm.",
        )

        # -- Voxel size ----------------------------------------------------
        # Smaller voxels -> finer alignment but cubic memory growth.
        # 10 nm is a good default for typical SMLM localization precision.
        self.voxel_size = QtWidgets.QDoubleSpinBox()
        self.voxel_size.setRange(1.0, 100.0)
        self.voxel_size.setDecimals(1)
        self.voxel_size.setValue(10.0)
        add_row(
            1,
            "Voxel size (nm):",
            self.voxel_size,
            "Bin width of the cross-correlation histograms.",
        )

        # -- Box half-width ------------------------------------------------
        # The box must be large enough to contain the entire structure
        # plus any plausible initial misalignment. 150 nm covers most
        # picked SMLM structures (nuclear pores, vesicles, ...).
        self.box_nm = QtWidgets.QDoubleSpinBox()
        self.box_nm.setRange(10.0, 1000.0)
        self.box_nm.setDecimals(1)
        self.box_nm.setValue(150.0)
        add_row(
            2,
            "Box half-width (nm):",
            self.box_nm,
            "Half-size of the cross-correlation box. Memory grows with "
            "(2 * box / voxel)^3 - keep it small for fine voxels.",
        )

        # -- Number of iterations ------------------------------------------
        # Each iteration re-estimates the consensus and re-aligns every
        # group to it. 5 iterations is typically converged; more are safe
        # but wasteful.
        self.iterations = QtWidgets.QSpinBox()
        self.iterations.setRange(1, 50)
        self.iterations.setValue(5)
        add_row(
            3,
            "Iterations:",
            self.iterations,
            "Number of rotation + translation alignment rounds.",
        )

        # Live memory estimate - helps the user avoid an out-of-memory
        # error on fine voxels with a large box.
        self.memory_label = QtWidgets.QLabel()
        self.memory_label.setWordWrap(True)
        grid.addWidget(self.memory_label, 4, 0, 1, 2)
        self.voxel_size.valueChanged.connect(self._update_memory)
        self.box_nm.valueChanged.connect(self._update_memory)
        self._update_memory()

        buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.StandardButton.Ok
            | QtWidgets.QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        grid.addWidget(buttons, 5, 0, 1, 2)

    def _update_memory(self) -> None:
        """Refresh the memory estimate shown under the input fields."""
        bins = self.n_bins()
        # Each voxel is a float64 (8 bytes); 3D histogram of shape bins^3.
        mbytes = bins**3 * 8 / 1024**2
        self.memory_label.setText(
            f"Grid: {bins}³ voxels (~{mbytes:.0f} MB per histogram)"
        )

    def n_bins(self) -> int:
        """Number of bins per axis for the current voxel / box settings."""
        return max(
            2,
            int(2 * self.box_nm.value() / max(self.voxel_size.value(), 1e-9)),
        )

    def values(self) -> dict:
        """Bundle all parameters into a plain dict for the worker thread."""
        return {
            "pixel_size": self.pixel_size.value(),
            "voxel_size": self.voxel_size.value(),
            "box_nm": self.box_nm.value(),
            "iterations": self.iterations.value(),
            "n_bins": self.n_bins(),
        }


class AlignWorker(QtCore.QThread):
    """Runs the iterative alignment off the GUI thread.

    Emits:

    * ``progress(it, n_it, done, n_groups)`` - while a single iteration is
      in flight, ``done`` groups have already been aligned.
    * ``iteration_done(locs)`` - after every iteration, so the Average
      window can display the current state.
    * ``succeeded(locs, transformations)`` - terminal signal, on success.
    * ``failed(traceback_str)`` - terminal signal, on exception.
    * ``aborted()`` - terminal signal, when the user interrupts.

    The worker owns the only mutable copy of the localizations. The GUI
    thread receives snapshots via the signals above, which are always
    fresh DataFrames so the two threads never share mutable state.
    """

    progress = QtCore.pyqtSignal(
        int, int, int, int
    )  # it, n_it, done, n_groups
    iteration_done = QtCore.pyqtSignal(object)  # locs
    succeeded = QtCore.pyqtSignal(object, object)  # locs, transformations
    failed = QtCore.pyqtSignal(str)
    aborted = QtCore.pyqtSignal()

    def __init__(self, locs: pd.DataFrame, params: dict):
        super().__init__()
        self.locs = locs.copy()
        self.params = params

    def run(self) -> None:  # noqa: C901 - linear, but long
        """QThread entry point. Catches everything so the GUI always sees
        a terminal signal (``succeeded``, ``failed`` or ``aborted``)."""
        try:
            self._run()
        except Exception:
            self.failed.emit(traceback.format_exc())

    def _run(self) -> None:
        """Actual alignment loop. See module docstring for the workflow."""
        locs = self.locs
        params = self.params
        pixel_size = params["pixel_size"]
        iterations = params["iterations"]
        box_nm = params["box_nm"]
        # Shared bin grid for every histogram in this run: the reference,
        # every group, and every iteration use exactly the same edges, so
        # voxels correspond one-to-one across all comparisons.
        edges = np.linspace(-box_nm, box_nm, params["n_bins"] + 1)

        indices = group_indices(locs)
        n_groups = len(indices)

        # Work on flat NumPy arrays rather than the DataFrame for speed;
        # they are pasted back into a DataFrame only when emitting signals.
        x = locs["x"].to_numpy(dtype=np.float64, copy=True)
        y = locs["y"].to_numpy(dtype=np.float64, copy=True)
        z = locs["z"].to_numpy(dtype=np.float64, copy=True)

        # ------------------------------------------------------------------
        # Step 1: center each group on its center of mass, as
        # ``average.com_align`` does (which only handles x and y). Doing
        # this in 3D here makes the initialization identical in spirit to
        # the built-in alignment and removes the largest translational
        # offsets before the iterative search.
        # ------------------------------------------------------------------
        transformations: dict[int, dict] = {}
        for group, idx in indices.items():
            com_x, com_y, com_z = (
                float(x[idx].mean()),
                float(y[idx].mean()),
                float(z[idx].mean()),
            )
            x[idx] -= com_x
            y[idx] -= com_y
            z[idx] -= com_z
            transformations[group] = {
                "com_transform": {
                    "com_x": com_x,
                    "com_y": com_y,
                    "com_z": com_z,
                },
                "cc_transform": {
                    "angle_deg": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "dz": 0.0,
                },
            }
        # Show the COM-aligned state immediately.
        self.iteration_done.emit(self._as_locs(locs, x, y, z))

        # ------------------------------------------------------------------
        # Step 2: iterative in-plane rotation + 3D translation
        # ------------------------------------------------------------------
        # At each iteration:
        #   1. Build a consensus histogram from all currently-aligned
        #      groups (this is the "reference").
        #   2. Independently align every group to that reference.
        #   3. Apply each group's transform and accumulate it into the
        #      per-group record.
        # Group alignment is parallelized across a ThreadPoolExecutor
        # because ``align_group`` is pure NumPy/SciPy work that releases
        # the GIL. BLAS oversubscription is capped via ``_single_threaded_blas``.
        max_workers = max(1, min(os.cpu_count() or 4, n_groups))
        for it in range(iterations):
            if self.isInterruptionRequested():
                self.aborted.emit()
                return

            # Consensus (reference) histograms on the shared grid.
            ref_hist, _ = np.histogramdd(
                (x * pixel_size, y * pixel_size, z), bins=(edges, edges, edges)
            )
            ref_2d = ref_hist.sum(axis=2)

            results: dict[int, tuple] = {}
            self.progress.emit(it + 1, iterations, 0, n_groups)
            with (
                _single_threaded_blas(),
                ThreadPoolExecutor(max_workers=max_workers) as pool,
            ):
                futures = {
                    pool.submit(
                        align_group,
                        x[idx],
                        y[idx],
                        z[idx],
                        ref_hist,
                        ref_2d,
                        edges,
                        pixel_size,
                    ): group
                    for group, idx in indices.items()
                }
                for done, future in enumerate(as_completed(futures), start=1):
                    if self.isInterruptionRequested():
                        # Best-effort cancellation: futures already running
                        # will finish, but no new ones start.
                        for pending in futures:
                            pending.cancel()
                        self.aborted.emit()
                        return
                    results[futures[future]] = future.result()
                    self.progress.emit(it + 1, iterations, done, n_groups)

            # Apply each group's transform to its localizations and record
            # the transform in the cumulative per-group record.
            for group, (angle_deg, dx, dy, dz) in results.items():
                idx = indices[group]
                rad = np.radians(angle_deg)
                cos_a, sin_a = np.cos(rad), np.sin(rad)
                x_rot = x[idx] * cos_a - y[idx] * sin_a
                y_rot = x[idx] * sin_a + y[idx] * cos_a
                x[idx] = x_rot + dx
                y[idx] = y_rot + dy
                z[idx] += dz
                compose(
                    transformations[group]["cc_transform"],
                    angle_deg,
                    dx,
                    dy,
                    dz,
                )

            # Let the GUI show the updated state after each iteration.
            self.iteration_done.emit(self._as_locs(locs, x, y, z))

        self.succeeded.emit(self._as_locs(locs, x, y, z), transformations)

    @staticmethod
    def _as_locs(
        locs: pd.DataFrame, x: np.ndarray, y: np.ndarray, z: np.ndarray
    ) -> pd.DataFrame:
        """Create a fresh DataFrame with updated x/y/z, preserving all
        other columns (frame, photons, sx, sy, ...)."""
        out = locs.copy()
        out["x"] = x
        out["y"] = y
        out["z"] = z
        return out


class Plugin:
    """Picasso plugin entry point.

    Picasso calls ``__init__(window)`` at load time and ``execute()`` when
    the user selects the plugin from the menu. We register two menu
    actions:

    * Run reference alignment (3D COM + iterative rotation/translation).
    * Apply the saved reference transforms to a target channel.
    """

    def __init__(self, window):
        self.name = "average"  # attached to the Average window
        self.window = window
        self.worker = None
        self.actions = []

    def execute(self):
        """Register the plugin's menu entries. Called once by Picasso."""
        menu = self.window.plugin_menu
        align = menu.addAction(
            "3D COM & 2D rotation cross-correlation (reference channel)"
        )
        align.triggered.connect(self.run_3d_alignment)
        apply_action = menu.addAction(
            "Apply saved reference transformations to target channel"
        )
        apply_action.triggered.connect(self.apply_transformations)
        self.actions = [align, apply_action]

    # -- helpers --------------------------------------------------------------

    def _error(self, message: str) -> None:
        """Show a warning dialog. Centralized so the message box style is
        consistent everywhere."""
        QtWidgets.QMessageBox.warning(self.window, PLUGIN_NAME, message)

    def _status(self, message: str) -> None:
        """Write to the Average window's status bar."""
        self.window.statusBar().showMessage(message)

    def _load(self, title: str, require_z: bool = True):
        """Prompt for an HDF5 file and load it.

        Returns ``(path, locs, info)`` on success, ``None`` on cancel or
        if the file is unusable. ``require_z=False`` is used only when the
        caller is certain 3D data is not required; currently both callers
        pass the default because the plugin is inherently 3D.

        Validation performed here:

        * The required columns exist (``group``, optionally ``z``).
        * ``x``/``y``/``z`` are cast to float64 for numerical stability.
        * The index is reset so subsequent positional indexing is safe.
        """
        path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.window, title, "", "HDF5 files (*.hdf5)"
        )
        if not path:
            return None
        try:
            locs, info = io.load_locs(path, qt_parent=self.window)
        except Exception as exc:  # noqa: BLE001 - surfaced to the user
            self._error(f"Could not load {os.path.basename(path)}:\n{exc}")
            return None

        missing = [
            c
            for c in (["group", "z"] if require_z else ["group"])
            if c not in locs.columns
        ]
        if missing:
            self._error(
                f"{os.path.basename(path)} is missing the "
                f"{', '.join(missing)} column(s). Load picked, 3D "
                "localizations."
            )
            return None

        locs = locs.reset_index(drop=True)
        locs = locs.astype(
            {c: np.float64 for c in ("x", "y", "z") if c in locs.columns}
        )
        return path, locs, info

    def _push_to_view(
        self,
        locs: pd.DataFrame,
        info: list[dict] | None = None,
        path: str | None = None,
        rescale: bool = False,
    ) -> None:
        """Show localizations in the Average window, mirroring ``View.open``.

        Localizations stay a DataFrame in the origin-centered frame the
        rest of the Average GUI expects, so File > Save and Process >
        Average keep working afterwards.

        ``rescale`` is set the first time a dataset is shown so the view
        fits the new data; subsequent updates keep the same zoom so the
        user can see alignment progress without the canvas jumping.
        """
        view = getattr(self.window, "view", None)
        if view is None:
            return
        view.locs = locs
        if info is not None:
            view.info = info
        if path is not None:
            view.path = path
            view.avg_history = []
        if rescale or not hasattr(view, "r"):
            # Radius that comfortably contains the data around the origin.
            view.r = 2 * np.sqrt((locs["x"] ** 2 + locs["y"] ** 2).mean())
            self.window.parameters_dialog.on_disp_px_size_changed()
        view.update_image()

    def _set_running(self, running: bool) -> None:
        """Enable / disable the plugin's actions and the GUI's own Average.

        Also hooks the Average window's Abort action to the worker thread
        (via ``view.thread``) so Ctrl+. interrupts this alignment rather
        than the built-in one.
        """
        for action in self.actions:
            action.setEnabled(not running)
        view = getattr(self.window, "view", None)
        if view is not None:
            view.running = running  # blocks the GUI's own Average while busy
        if hasattr(self.window, "abort_action"):
            self.window.abort_action.setEnabled(running)

    # -- reference channel ----------------------------------------------------

    def run_3d_alignment(self):
        """Entry point for the ``3D COM & 2D rotation cross-correlation`` menu item."""
        loaded = self._load("Select reference channel localizations (.hdf5)")
        if loaded is None:
            return
        self.ref_path, locs, info = loaded

        # Default pixel size comes from the HDF5 metadata; the user can
        # override it in the parameters dialog.
        pixel_size = lib.get_from_metadata(info, "Pixelsize") or 130.0
        dialog = ParametersDialog(self.window, float(pixel_size))
        if dialog.exec() != QtWidgets.QDialog.DialogCode.Accepted:
            return
        params = dialog.values()

        # Ensure the HDF5 metadata carries every key Picasso needs later.
        self.ref_info = ensure_required_metadata(
            info, locs, params["pixel_size"]
        )
        # Show the raw data first; the worker will keep updating the view
        # as it iterates.
        self._push_to_view(
            locs, info=self.ref_info, path=self.ref_path, rescale=True
        )

        # Wire the worker's signals to the GUI slots below. All GUI work
        # happens in slots on the main thread; the worker only computes.
        self.worker = AlignWorker(locs, params)
        self.worker.progress.connect(self._on_progress)
        self.worker.iteration_done.connect(self._on_iteration)
        self.worker.succeeded.connect(self._on_succeeded)
        self.worker.failed.connect(self._on_failed)
        self.worker.aborted.connect(self._on_aborted)
        self.worker.finished.connect(lambda: self._set_running(False))

        # Route the window's Abort action (Ctrl+.) at our thread.
        view = getattr(self.window, "view", None)
        if view is not None:
            view.thread = self.worker
        self._set_running(True)
        self._status("Aligning reference channel...")
        self.worker.start()

    def _on_progress(self, it, n_it, done, n_groups):
        """Update the status bar during alignment."""
        self._status(
            f"{PLUGIN_NAME}: iteration {it}/{n_it} - "
            f"{done}/{n_groups} groups aligned"
        )

    def _on_iteration(self, locs):
        """Refresh the displayed localizations after each iteration."""
        self._push_to_view(locs)

    def _on_aborted(self):
        """User pressed Abort (Ctrl+.)."""
        self._status(f"{PLUGIN_NAME}: aborted.")

    def _on_failed(self, message):
        """Worker raised an exception: show the last line in a dialog and
        the full traceback to stdout for debugging."""
        print(message)
        self._error(f"Alignment failed:\n\n{message.strip().splitlines()[-1]}")
        self._status(f"{PLUGIN_NAME}: failed.")

    def _on_succeeded(self, locs, transformations):
        """Alignment converged: save the aligned HDF5 and the transform YAML."""
        self._push_to_view(locs)

        # Output paths are derived from the reference file so that the
        # pair of outputs is easy to associate with the input.
        base = os.path.splitext(self.ref_path)[0]
        hdf5_path = f"{base}_3DAligned.hdf5"
        yaml_path = f"{base}_3DTransformations.yaml"
        params = dict(self.worker.params)

        try:
            save_aligned_locs(hdf5_path, locs, self.ref_info, params)
            self._save_transformations(yaml_path, transformations, params)
        except Exception as exc:  # noqa: BLE001 - surfaced to the user
            traceback.print_exc()
            self._error(f"Alignment finished but saving failed:\n{exc}")
            return

        self._status(f"{PLUGIN_NAME}: done.")
        QtWidgets.QMessageBox.information(
            self.window,
            PLUGIN_NAME,
            "Reference alignment completed.\n\n"
            f"Aligned reference:\n{hdf5_path}\n\n"
            f"Transformations:\n{yaml_path}",
        )

    def _save_transformations(
        self, path: str, transformations: dict, params: dict
    ) -> None:
        """Write the per-group transforms to a YAML file.

        The file starts with a ``__meta__`` block that records the plugin
        version, the reference file name, the coordinate convention, and
        the order of operations needed to replay the transform. This is
        what makes the transforms self-describing for the target-channel
        step (and for any external analysis script).
        """
        document = {
            "__meta__": {
                "generated_by": f"Picasso {__version__} - {PLUGIN_NAME}",
                "reference_file": os.path.basename(self.ref_path),
                "frame": (
                    "x/y in camera pixels, z in nm, groups centered on the "
                    "origin; the canvas offset is added on save"
                ),
                "order": (
                    "subtract com_transform, then rotate by "
                    "cc_transform.angle_deg, then add cc_transform.d[xyz]"
                ),
                **params,
            },
            **{int(g): t for g, t in transformations.items()},
        }
        with open(path, "w") as f:
            yaml.dump(document, f, default_flow_style=False)

    # -- target channel -------------------------------------------------------

    def apply_transformations(self):
        """Entry point for the ``Apply saved reference transformations``
        menu item.

        Reads the reference transform YAML, loads a target channel, and
        replays the transforms group-by-group. Groups present in the
        target but absent from the YAML are dropped with a note, since
        they cannot be aligned.
        """
        # -- 1. Read the transforms ----------------------------------------
        trans_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self.window,
            "Select reference transformations (*_3DTransformations.yaml)",
            "",
            "YAML files (*.yaml)",
        )
        if not trans_path:
            return
        try:
            transformations, meta = load_transformations(trans_path)
        except Exception as exc:  # noqa: BLE001 - surfaced to the user
            self._error(
                f"Could not read {os.path.basename(trans_path)}:\n{exc}"
            )
            return
        if not transformations:
            self._error("No transformations found in the selected file.")
            return

        # -- 2. Load the target channel ------------------------------------
        loaded = self._load("Select target channel localizations (.hdf5)")
        if loaded is None:
            return
        target_path, locs, info = loaded

        indices = group_indices(locs)
        x = locs["x"].to_numpy(dtype=np.float64, copy=True)
        y = locs["y"].to_numpy(dtype=np.float64, copy=True)
        z = locs["z"].to_numpy(dtype=np.float64, copy=True)

        # -- 3. Replay transforms group-by-group ---------------------------
        applied = {}
        for group, transform in transformations.items():
            idx = indices.get(group)
            if idx is None:
                # Group exists in the reference but not in the target:
                # nothing to align, skip it.
                continue
            x[idx], y[idx], z[idx] = apply_transform(
                x[idx],
                y[idx],
                z[idx],
                transform["com_transform"],
                transform["cc_transform"],
            )
            applied[group] = transform

        if not applied:
            self._error(
                "No group in the target channel matches the transformations. "
                "Both channels must be picked with the same group ids."
            )
            return

        # -- 4. Keep only the groups that were actually transformed --------
        # Preserve the original row order so downstream tools (frame,
        # photons, ...) still make sense.
        missing = sorted(set(indices) - set(applied))
        keep = np.sort(np.concatenate([indices[g] for g in applied]))
        locs = locs.iloc[keep].copy()
        locs["x"] = x[keep]
        locs["y"] = y[keep]
        locs["z"] = z[keep]
        locs = locs.reset_index(drop=True)

        # -- 5. Save and display -------------------------------------------
        # Pixel size priority: value stored in the transform YAML, then
        # target metadata, then the plugin default.
        pixel_size = (
            meta.get("pixel_size")
            or lib.get_from_metadata(info, "Pixelsize")
            or 130.0
        )
        info = ensure_required_metadata(info, locs, float(pixel_size))
        self._push_to_view(locs, info=info, path=target_path, rescale=True)

        base = os.path.splitext(target_path)[0]
        hdf5_path = f"{base}_3DAligned.hdf5"
        try:
            save_aligned_locs(
                hdf5_path,
                locs,
                info,
                {
                    "applied_from": os.path.basename(trans_path),
                    "groups": len(applied),
                },
            )
        except Exception as exc:  # noqa: BLE001 - surfaced to the user
            traceback.print_exc()
            self._error(f"Saving failed:\n{exc}")
            return

        # Mention dropped groups in the confirmation dialog so the user
        # does not silently lose data.
        note = (
            f"\n\n{len(missing)} target group(s) had no transformation and "
            "were dropped."
            if missing
            else ""
        )
        self._status(f"{PLUGIN_NAME}: transformations applied.")
        QtWidgets.QMessageBox.information(
            self.window,
            PLUGIN_NAME,
            f"Transformations applied to {len(applied)} group(s).\n\n"
            f"Aligned target:\n{hdf5_path}{note}",
        )